language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - npm install -g node-gyp eslint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
script:
  - jdk_switcher use oraclejdk8
  - npm run travis
  - npm run lint
dist: trusty
sudo: required
notifications:
  email: false
